#ifndef KCRYPTOV_KCV_KSHELLV_H
#define KCRYPTOV_KCV_KSHELLV_H

#define KCV_KSHELLV_LISTENING_PORT 8090
#define KCV_KSHELLV_HOSTNAME "KCV"
#define KCV_KSHELLV_BANNER "Welcome To The KCV Framework"


int ksv_shell_start();


#endif //KCRYPTOV_KCV_KSHELLV_H
